### ISSUE TITLE
swo串口

### ISSUE THREAD

**Issue by Zy19930907** [windowsair/wireless-esp8266-dap#11]
大佬可以把串口加上吗？

**Comment by windowsair** [comment]
@Zy19930907 :
感谢您提起这个。
目前IO资源比较紧张，短时间内没有加入SWO的计划。

Thanks for raising this.
 Currently IO resources are limited and there are no plans to join SWO anytime soon.

**Comment by windowsair** [comment]
不过我们仍然可以通过IO复用的方式实现这一点。目前正在准备发布一个新版本，在这个版本完成之后，应该可以考虑加入SWO. 😂

But we can still achieve this by IO reuse. A new release is being prepared, and after this version is completed, we should be able to consider adding SWO.  😂

**Comment by Zy19930907** [comment]
谢谢支持，我这边按照您的工程移植了一个Arduino版的工程到esp32上，现在esp32 IO比较充足，您这边考虑支持esp32吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "windowsair/wireless-esp8266-dap"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月14日(星期天) 中午11:48
收件人:&nbsp;"windowsair/wireless-esp8266-dap"<wireless-esp8266-dap@noreply.github.com&gt;;
抄送:&nbsp;"351389258"<351389258@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [windowsair/wireless-esp8266-dap] swo串口 (#11)





 
不过我们仍然可以通过IO复用的方式实现这一点。目前正在准备发布一个新版本，在这个版本完成之后，应该可以考虑加入SWO. 😂
 
But we can still achieve this by IO reuse. A new release is being prepared, and after this version is completed, we should be able to consider adding SWO.  😂

**Comment by windowsair** [comment]
有的，我们是有这个打算。您已经移植完毕了吗？进展如何呢😊

Yes, we do intend to do that. Have you finished porting yet? How is it going?😊

**Comment by Zy19930907** [comment]
目前移植到esp32，Arduino工程，swd调试正常，我本来是想发给您的，有用的话可以参考一下，但是好像您的github邮箱拒收了，工程17M，您可以提供一个其他的邮箱我发给您吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "windowsair/wireless-esp8266-dap"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月14日(星期天) 中午1:30
收件人:&nbsp;"windowsair/wireless-esp8266-dap"<wireless-esp8266-dap@noreply.github.com&gt;;
抄送:&nbsp;"351389258"<351389258@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [windowsair/wireless-esp8266-dap] swo串口 (#11)





 
有的，我们是有这个打算。您已经移植完毕了吗？进展如何呢😊
 
Yes, we do intend to do that. Have you finished porting yet? How is it going?😊

**Comment by windowsair** [comment]
辛苦了，这个移植的工作量不小。🥰

您可以直接发到msdn_01#sina.com的邮箱（QQ同号）

**Comment by Yecgaa1** [comment]
> 目前移植到esp32，Arduino工程，swd调试正常，我本来是想发给您的，有用的话可以参考一下，但是好像您的github邮箱拒收了，工程17M，您可以提供一个其他的邮箱我发给您吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "windowsair/wireless-esp8266-dap" <notifications@github.com&gt;; 发送时间:&nbsp;2021年2月14日(星期天) 中午1:30 收件人:&nbsp;"windowsair/wireless-esp8266-dap"<wireless-esp8266-dap@noreply.github.com&gt;; 抄送:&nbsp;"351389258"<351389258@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [windowsair/wireless-esp8266-dap] swo串口 (#11) 有的，我们是有这个打算。您已经移植完毕了吗？进展如何呢😊 Yes, we do intend to do that. Have you finished porting yet? How is it going?😊 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

我看到您对这个仓库的分支https://github.com/Zy19930907/wireless-esp8266-dap，请问您这个仓库是您已经成功移植到Esp32了吗

**Comment by windowsair** [comment]
Hi，@Yecgaa1

感谢您的关注，我已经和这位作者联系上了，他的工程暂时还未发布。

本项目的移植工作也正在进行中，可能不久之后发布。

**Comment by Yecgaa1** [comment]
好的，我非常期待这个移植可以突破由于tcp传输速度瓶颈所导致的性能瓶颈

**Comment by windowsair** [comment]
> 好的，我非常期待这个移植可以突破由于tcp传输速度瓶颈所导致的性能瓶颈

@Yecgaa1 关于稳定性和性能请查看这个线程： #4 

esp32带来的性能提升可能感知不强。。。

**Comment by Yecgaa1** [comment]
> > 好的，我非常期待这个移植可以突破由于tcp传输速度瓶颈所导致的性能瓶颈
> 
> @Yecgaa1 关于稳定性和性能请查看这个线程： #4
> 
> esp32带来的性能提升可能感知不强。。。

我看到了你最新的测试成果
或许你可以尝试做一下发送器，或许可以绕过usbip的限制。虽然我可以猜到这其中的难度
当然，我仍然期待esp32可以带来一定提升，当然这需要看测试结果

**Comment by Yecgaa1** [comment]
同时对esp32的适配也有利于swo的加入

**Comment by kaide6** [comment]
> 大佬可以把串口加上吗？

大佬，烧录成功了吗，我现在连原文件还没编译成功，可以发一份，编译好的文件给我吗

**Comment by windowsair** [comment]
> 现在还没有串口，编译好的版本可以看看release页面里的https://github.com/windowsair/wireless-esp8266-dap/releases
> 
> > 大佬可以把串口加上吗？
> 
> 大佬，烧录成功了吗，我现在连原文件还没编译成功，可以发一份，编译好的文件给我吗

现在还没有串口，编译好的版本可以看看release页面里的https://github.com/windowsair/wireless-esp8266-dap/releases

**Comment by kaide6** [comment]
> > 现在还没有串口，编译好的版本可以看看release页面里的https://github.com/windowsair/wireless-esp8266-dap/releases
> > > 大佬可以把串口加上吗？
> > 
> > 
> > 大佬，烧录成功了吗，我现在连原文件还没编译成功，可以发一份，编译好的文件给我吗
> 
> 现在还没有串口，编译好的版本可以看看release页面里的https://github.com/windowsair/wireless-esp8266-dap/releases

好的感谢，刚开始接触，是在download中选择bootloadder.bin和
esp8266dap_app.bin就可以了吗
![image](https://user-images.githubusercontent.com/62867054/127869659-e1deae52-b56d-4198-8912-2f9905559d58.png)

**Comment by windowsair** [comment]
@kaide6 用full的，从0x00开始烧录

**Comment by windowsair** [comment]
@kaide6 可以参考下这个
![image](https://user-images.githubusercontent.com/17078589/127870168-2abb3e99-ecaf-4625-9104-aaf9cd048381.png)

**Comment by kaide6** [comment]
> @kaide6 可以参考下这个
> ![image](https://user-images.githubusercontent.com/17078589/127870168-2abb3e99-ecaf-4625-9104-aaf9cd048381.png)
是这样吗？
![image](https://user-images.githubusercontent.com/62867054/127870431-307c2aba-1ca1-4e50-98f4-d2cbfd4b1092.png)

**Comment by windowsair** [comment]
@kaide6  上面的没问题，下面的flash size和spi选项需要根据板子来选

**Comment by kaide6** [comment]
有群或者B站号吗？

**Comment by windowsair** [comment]
> 有群或者B站号吗？

没有，可以在github上问，建议新开个issue，或者在discussion里讨论

**Comment by windowsair** [comment]
朋友们好，暂时不考虑加入SWO功能了。不过有加入其他形式串口的打算， 我们在 #21 中进行详细讨论。

Hi all, SWO feature will not be added in the future. But a lightweight uart bridge is possible. See:  #21
