### ISSUE TITLE
v0.1.3-alpha is NOW OUT!!!

### ISSUE THREAD

**Issue by windowsair** [windowsair/wireless-esp8266-dap#14]
https://github.com/windowsair/wireless-esp8266-dap/releases/tag/v0.1.3-alpha

Now we support 3-wire spi, you dont need to physically connect GPIO12 to GPIO13:

![image](https://user-images.githubusercontent.com/17078589/110634976-90194080-81e5-11eb-9914-4d5414162e94.png)

**Comment by Yecgaa1** [comment]
如果我已经连接了GPIO12物理连接到GPIO13，我还可以使用这个版本的固件吗？

**Comment by windowsair** [comment]
> 如果我已经连接了GPIO12物理连接到GPIO13，我还可以使用这个版本的固件吗？

可以
