### ISSUE TITLE
GitHub release failed with status: 422

### ISSUE THREAD

**Issue by Yecgaa1** [windowsair/wireless-esp8266-dap#15]
![image](https://user-images.githubusercontent.com/38446391/111021971-db606880-840a-11eb-8ed8-574d599634b2.png)
Opps
我不知道如何解决这个问题

**Comment by Yecgaa1** [comment]
我手动终止了它因为它会不断尝试知道api调用次数过大

**Comment by windowsair** [comment]
https://github.com/windowsair/wireless-esp8266-dap/commit/2bf0006241658152ba871b9589714a42c227c667

已修复，重新试试

**Comment by Yecgaa1** [comment]
好的，它正常了！
