### ISSUE TITLE
EN脚需要被拉高

### ISSUE THREAD

**Issue by Yecgaa1** [windowsair/wireless-esp8266-dap#16]
![image](https://user-images.githubusercontent.com/38446391/111035353-14bdc600-8455-11eb-91f7-bcef8fbb029f.png)
EN脚需要被拉高，然而README提供的原理图没有这个

**Comment by windowsair** [comment]
这里只给出关键的引脚，其他的设计请参考乐鑫的相关指南

**Comment by Yecgaa1** [comment]
好的，不过可能顺带标出来会更加友好
毕竟vcc已经被标出的情况下

**Comment by windowsair** [comment]
实际上按照乐鑫的说法，EN引脚需要增加RC电路，具体的值还需要根据模组和电路给出
