### ISSUE TITLE
waiting for host？？

### ISSUE THREAD

**Issue by Yecgaa1** [windowsair/wireless-esp8266-dap#17]
ets Jan  8 2013,rst cause:1, boot mode:(7,0)

waiting for host

我在串口里收到了这个消息，并且是在烧录之后

我使用的烧录命令是

 python "C:\Users\xtx\OneDrive - xutongxin\ESP8266\DAP\pytool\esptool\esptool.py" -p COM16 -b 921600 --after hard_reset write_flash --flash_mode dio --flash_size 16MB --flash_freq 80m 0x0 bootloader.bin 0x8000 partition-table.bin 0x10000 esp8266_dap.bin

烧录结果是

Hash of data verified.

Leaving...
Hard resetting via RTS pin...

很抱歉，我对这个芯片确实不够熟悉，希望你可以解答我，再次感谢

**Comment by windowsair** [comment]
boot mode不对，gpio15不应该被拉高

**Comment by Yecgaa1** [comment]
好的

**Comment by windowsair** [comment]
15留给灯了，按照原理图应该不至于拉高吧
