### ISSUE TITLE
The question about "RDDI-DAP Error"

### ISSUE THREAD

**Issue by LanT33** [windowsair/wireless-esp8266-dap#20]
连上设备后，第一次打开keil的调试器设置窗口，看到调试器连接成功
after connect to the DAP,The first time I open the keil debugger settings window, the debugger connection is successful.

<img width="468" alt="第一次打开界面" src="https://user-images.githubusercontent.com/81430540/131211181-fe8cd9c6-cdc2-4f55-ad1b-3bc1057eb1af.PNG">

然后关闭窗口，第二次打开设置窗口，显示如下错误
I close the setting window,and open it again,it show the error as the following picture:

<img width="502" alt="第二次打开界面" src="https://user-images.githubusercontent.com/81430540/131211216-f68e473e-d08f-40b8-95e2-4c696989aa12.PNG">

之后无论开关几次，都显示上述错误。
The above error is displayed no matter how many times I turn it on and off.

请问应该如何解决？
How can I solve it？

**Comment by LanT33** [comment]
已经尝试过减小Max Clock和重新插线，仍未解决问题
I have been attempted to reduce Max Clock and rewire, but they are not available.

**Comment by windowsair** [comment]
试试1MHz左右的速度看看？

**Comment by LanT33** [comment]
> 试试1MHz左右的速度看看？

重新开启测试模式后，程序运作正常，非常感谢你的开源！
Well,After reopen test mod,everything become find.Thank you for your open-source!

**Comment by windowsair** [comment]
Hi, @LanT33 
感谢您的反馈，这种情况一般是电路连接问题，建议3v3（最好接上），gnd，sclk，swdio均使用较短的线连接
还有一种情况网络干扰，esp8266受5G wifi的影响很大，如果一直显示这个可以试试看断开usbip重新连接看看

**Comment by windowsair** [comment]
我要关闭这个问题了，如果您有任何疑问，欢迎重新打开它
