### ISSUE TITLE
Which version of usbip are you using?

### ISSUE THREAD

**Issue by Iezuni** [windowsair/wireless-esp8266-dap#22]
Which version of usbip are you using?
我在使用usbip-win-0.3.5连接时,发现并没有usbip.exe attach_ude 这条命令并且报错

**Comment by windowsair** [comment]
Hi, @lezuni

这是usbip-win的问题。在usbip-win 0.3.5中attach_ude 已经被废弃，直接用attch就行了

**Comment by Iezuni** [comment]
使用命令 `.\usbip.exe attach -r 192.168.43.60 -b 1-1` 连接之后报错
`usbip: error: vhci driver is not loaded`

 esp8266 输出:
```
Socket accepted

Handling dev attach request...

Sending header...

Sending device info...

* GET 0x02 CONFIGURATION DESCRIPTOR

Sending only first part of CONFIG

* GET 0x01 DEVICE DESCRIPTOR

* GET 0x02 CONFIGURATION DESCRIPTOR

Sending only first part of CONFIG

* GET 0x02 CONFIGURATION DESCRIPTOR

Sending ALL CONFIG

recv failed: errno 104
Shutting down socket and restarting...
```

**Comment by windowsair** [comment]
> 使用命令 `.\usbip.exe attach -r 192.168.43.60 -b 1-1` 连接之后报错 `usbip: error: vhci driver is not loaded`
> 
> esp8266 输出:
> 
> ```
> Socket accepted
> 
> Handling dev attach request...
> 
> Sending header...
> 
> Sending device info...
> 
> * GET 0x02 CONFIGURATION DESCRIPTOR
> 
> Sending only first part of CONFIG
> 
> * GET 0x01 DEVICE DESCRIPTOR
> 
> * GET 0x02 CONFIGURATION DESCRIPTOR
> 
> Sending only first part of CONFIG
> 
> * GET 0x02 CONFIGURATION DESCRIPTOR
> 
> Sending ALL CONFIG
> 
> recv failed: errno 104
> Shutting down socket and restarting...
> ```
> 
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)

看样子是usbip驱动没有装，检查下设备管理器有没有这一项：
![image](https://user-images.githubusercontent.com/17078589/143684341-fff8ac0b-cb3d-4d11-95a8-6aa0df52508d.png)

**Comment by Iezuni** [comment]
没有这一项，，这个驱动是怎么安装呢？

**Comment by windowsair** [comment]
具体还请参考usbip-win的文档，需要先安装证书，然后使用install选项安装驱动

**Comment by Iezuni** [comment]
我刚刚已经安装了usbip的驱动，但是设备管理器的界面上显示了一个三角形 ，usbip install 显示已经成功安装 再次使用命令连接时 同样显示一样的错误 还有其他的办法吗

**Comment by windowsair** [comment]
试下系统进测试模式再安装？

**Comment by Iezuni** [comment]
虽然显示成功连接上了 但是不能在通用串行总线上找到esp8266😥 keil也没有cmsis dap设备

**Comment by windowsair** [comment]
如果设备管理器看不到，就是没有连接上。
出于好奇，您用的是什么系统？

**Comment by Iezuni** [comment]
刚刚没刷新 设备管理器上是有esp8266的 只是keil无法连接
系统是win10 20h2

**Comment by windowsair** [comment]
能看看8266的串口输出吗？还有就是keil的版本是不是太旧了？

**Comment by Iezuni** [comment]
这个是串口输出
```
Handling dev attach request...

Sending header...

Sending device info...

* GET 0x02 CONFIGURATION DESCRIPTOR

Sending only first part of CONFIG

* GET 0x01 DEVICE DESCRIPTOR

* GET 0x02 CONFIGURATION DESCRIPTOR

Sending only first part of CONFIG

* GET 0x02 CONFIGURATION DESCRIPTOR

Sending ALL CONFIG

* SET CONFIGURATION

* SET INTERFACE

* GET 0x0F BOS DESCRIPTOR

* GET MSOS 2.0 vendor-specific descriptor

** REQUESTED list of supported languages

* GET STATUS

** REQUESTED list of supported languages

```
keil 版本为5.25

**Comment by windowsair** [comment]
我不太确定5.25是不是太旧了，网上好像有类似的问题，可以替换dll，或者更新keil来解决这个问题

**Comment by windowsair** [comment]
我这边先试试看5.25能不能用吧

**Comment by windowsair** [comment]
这是我测试的结果。值的注意的是，0.3.5版本的usbip如果重复使用attach命令进行连接，而没有显式使用detach断开连接的话，可能会出现一些奇怪的问题
![image](https://user-images.githubusercontent.com/17078589/143765867-5712287b-30eb-4c42-9370-cf417627d958.png)

**Comment by Iezuni** [comment]
今天我再尝试的时候 在不关掉驱动程序强制签名时 usbip无法验证签名 在不验证签名时 我的电脑无法启动.....😰

**Comment by windowsair** [comment]
可以试下进测试模式，这样不用每次重启都进那个禁用驱动强制要求签名的模式

**Comment by Iezuni** [comment]
刚刚试了一下 我进入测试模式后会无限蓝屏

**Comment by Iezuni** [comment]
我可能需要考虑使用其他的办法来实现那远程下载了

**Comment by windowsair** [comment]
好吧= =这可能是系统问题，要不先把驱动卸载了，用旧的0.3.0版本的usbip？

**Comment by windowsair** [comment]
0.3.0版本的安装是install_ude，连接是attch_ude，这个有输入对么😳

**Comment by windowsair** [comment]
还要注意下安装前得手动卸载原有的旧驱动

**Comment by Iezuni** [comment]
导致问题的应该是自签名的驱动 ,如果有办法解决驱动签名的问题估计才能解决问题....

**Comment by windowsair** [comment]
如果真是签名问题，那可能暂时没办法了，上游的usbip项目暂时没有签名的计划😂

**Comment by windowsair** [comment]
@Iezuni 

目前上游的usbip更新了0.3.6的开发版本，在这个版本中驱动已经经过微软的签名，无需安装证书。

https://github.com/cezanne/usbip-win/releases/tag/v0.3.6-dev

**Comment by windowsair** [comment]
> @windowsair 我这边驱动也安装上了，设备管理器里也出现设备了，但是keil还是没认到 ![image](https://user-images.githubusercontent.com/9473678/207500012-9fe4422c-44e7-4266-9f4e-9e7a01f8cca7.png)
> 
> ![image](https://user-images.githubusercontent.com/9473678/207500105-64c8ae5b-4bee-4289-93eb-051098113315.png)

什么版本的usbip？ 串口有何输出？

**Comment by JustQY** [comment]
最新的0.3.6

![image](https://user-images.githubusercontent.com/9473678/207500595-304079f7-9d4d-4704-8512-d7af2411749d.png)

**Comment by JustQY** [comment]
@windowsair 
更新后可以了。发现一个情况，必须设置频率为10Mhz才行
