### ISSUE TITLE
如果做U盘烧录

### ISSUE THREAD

**Issue by neophack** [windowsair/wireless-esp8266-dap#25]
可以做一个虚拟U盘拖放烧录的功能么daplink有代码可以参考https://github.com/ARMmbed/DAPLink/blob/main/source/usb/msc/usbd_msc.c

**Comment by windowsair** [comment]
Hi, @neophack 

有在考虑这个计划。不过既然是无线的，可以直接用网页上传，更方便些

**Comment by neophack** [comment]
网页也不错，可以不用usbip也可以工作

**Comment by windowsair** [comment]
网页版本的已经支持
https://github.com/windowsair/elaphure-dap.js
