### ISSUE TITLE
release的固件无法正常运行

### ISSUE THREAD

**Issue by yzl893** [windowsair/wireless-esp8266-dap#33]
硬件是nodemcu，开机打印信息：

![image](https://user-images.githubusercontent.com/31109168/160312415-edb3f412-2521-4d32-bbcc-ebb2bd05c4f0.png)
下载设置：
![image](https://user-images.githubusercontent.com/31109168/160312441-3a81897c-8059-4328-9eb5-1ecfca64b5a1.png)

**Comment by yzl893** [comment]
修改SPI MODE为DIO后打印load partition table error
![image](https://user-images.githubusercontent.com/31109168/160312728-ac4c8ce7-89da-4dd6-adcd-26e2c8c87922.png)

**Comment by windowsair** [comment]
Hi， @yzl893 
下载固件的时候勾选Donotchgbin试试

**Comment by yzl893** [comment]
> Hi， @yzl893 下载固件的时候勾选Donotchgbin试试

还是不行，似乎是因为手里的8266不支持QIO的缘故，但是下载的时候设置成DOUT好像也没有用
![image](https://user-images.githubusercontent.com/31109168/160316059-62ab318f-7d63-4da2-95eb-7cd2d2ed9bd5.png)

**Comment by windowsair** [comment]
看样子没有烧录成功，可以多改几个烧录选项试试

**Comment by LDEDA4587** [comment]
我的nodemcu，32Mbit，使用如下烧录设置：
![ESP-12F](https://user-images.githubusercontent.com/60053330/195344366-0e9cbb6f-2646-401e-a60e-5b36078df5ab.JPG)
上电启动后打印信息如下：
![ESP-12F_Boot](https://user-images.githubusercontent.com/60053330/195344559-8197473e-44ca-4322-9eea-8d7687899efe.JPG)
应该可以理解为烧录成功，但是此时如果按RST复位，将不能正常启动，打印信息如下：
![ESP-12F_RST](https://user-images.githubusercontent.com/60053330/195344897-5ec99708-a8db-4673-a790-04868c1c99c6.JPG)
如果再次上电启动，nodemcu可以正常连接热点，上位机也可以正常运行。

**Comment by windowsair** [comment]
按RST后改变了某些引脚的电平，bootloader没有正常启动，而是进入到烧录模式

> 我的nodemcu，32Mbit，使用如下烧录设置： ![ESP-12F](https://user-images.githubusercontent.com/60053330/195344366-0e9cbb6f-2646-401e-a60e-5b36078df5ab.JPG) 上电启动后打印信息如下： ![ESP-12F_Boot](https://user-images.githubusercontent.com/60053330/195344559-8197473e-44ca-4322-9eea-8d7687899efe.JPG) 应该可以理解为烧录成功，但是此时如果按RST复位，将不能正常启动，打印信息如下： ![ESP-12F_RST](https://user-images.githubusercontent.com/60053330/195344897-5ec99708-a8db-4673-a790-04868c1c99c6.JPG) 如果再次上电启动，nodemcu可以正常连接热点，上位机也可以正常运行。
