### ISSUE TITLE
中文版wiki有误

### ISSUE THREAD

**Issue by ws2bhhh** [windowsair/wireless-esp8266-dap#36]
实际在更改WiFi接入点时需要将接入点加入wifi_list而不是更改WIFI_SSID和WIFI_PASS字段

**Comment by windowsair** [comment]
欢迎提出pr





------------------ 原始邮件 ------------------
发件人: ws2bhhh ***@***.***&gt;
发送时间: 2022年7月29日 03:00
收件人: windowsair/wireless-esp8266-dap ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [windowsair/wireless-esp8266-dap] 中文版wiki有误 (Issue #36)
