### ISSUE TITLE
软件能支持这个基于ESP32-S3的二合一调试器嘛

### ISSUE THREAD

**Issue by jumbo77** [windowsair/wireless-esp8266-dap#37]
https://oshwhub.com/cqzww/WiFi-USB-DAPLink
基于ESP32-S3的二合一调试器，支持USB和WiFi连接模式，兼容DAPLink调试器协议，可以直接替代传统DAP调试器。通过WiFi连接时也是模拟一个DAP调试器，对使用者是透明的，无需改变配置即可使用。WiFI连接时可以不受距离限制，甚至可以异地调试，以及多人共享。

**Comment by windowsair** [comment]
不太清楚，这个不是我做的，我也不知道他的软件实现是什么样的

**Comment by windowsair** [comment]
类似的有https://github.com/windowsair/elaphureLink
感兴趣的话可以看看
