### ISSUE TITLE
ESP32 encounter "RDDI-DAP ERROR" and "SWD/JTAG Communication Failure"

### ISSUE THREAD

**Issue by sczh01** [windowsair/wireless-esp8266-dap#38]
description:
Target Keil can't communicate with ESP32. 
![image](https://user-images.githubusercontent.com/287193/189159720-5563eff2-da12-4d7b-b3e0-6524ef0bfb4d.png)

Test Condition:
1.Keil version: 5.30
2.Usbip version: 0.36-dev
3.ESP32-s(Node ESP32-s) with IDF 4.3.2

Debug information:
1. esp32 uart information:
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:7564
ho 0 tail 12 room 4
load:0x40078000,len:15604
load:0x40080400,len:4392
entry 0x4008069c
I (28) boot: ESP-IDF v4.3.2 2nd stage bootloader
I (28) boot: compile time 00:32:47
I (29) boot: chip revision: 1
I (31) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (38) qio_mode: Enabling default flash chip QIO
I (44) boot.esp32: SPI Speed      : 80MHz
I (48) boot.esp32: SPI Mode       : QIO
I (53) boot.esp32: SPI Flash Size : 2MB
I (57) boot: Enabling RNG early entropy source...
I (63) boot: Partition Table:
I (66) boot: ## Label            Usage          Type ST Offset   Length
I (74) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (81) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (89) boot:  2 factory          factory app      00 00 00010000 00100000
I (96) boot: End of partition table
I (100) boot_comm: chip revision: 1, min. application chip revision: 0
I (107) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=15aach ( 88748) map
I (140) esp_image: segment 1: paddr=00025ad4 vaddr=3ffb0000 size=03e18h ( 15896) load
I (146) esp_image: segment 2: paddr=000298f4 vaddr=40080000 size=06724h ( 26404) load
I (155) esp_image: segment 3: paddr=00030020 vaddr=400d0020 size=7d31ch (512796) map
I (296) esp_image: segment 4: paddr=000ad344 vaddr=40086724 size=11d1ch ( 72988) load
I (320) esp_image: segment 5: paddr=000bf068 vaddr=50000000 size=00010h (    16) load
I (332) boot: Loaded app from partition at offset 0x10000
I (333) boot: Disabling RNG early entropy source...
I (344) cpu_start: Pro cpu up.
I (344) cpu_start: Starting app cpu, entry point is 0x40081610
I (0) cpu_start: App cpu up.
I (358) cpu_start: Pro cpu start user code
I (358) cpu_start: cpu freq: 240000000
I (358) cpu_start: Application information:
I (363) cpu_start: Project name:     wireless_esp_dap
I (369) cpu_start: App version:      v0.2.0-2-g6650ac7-dirty
I (375) cpu_start: Compile time:     Sep  8 2022 00:32:19
I (381) cpu_start: ELF file SHA256:  5e8086ad884c2b1b...
I (387) cpu_start: ESP-IDF:          v4.3.2
I (392) heap_init: Initializing. RAM available for dynamic allocation:
I (399) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (405) heap_init: At 3FFB8750 len 000278B0 (158 KiB): DRAM
I (411) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (418) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (424) heap_init: At 40098440 len 00007BC0 (30 KiB): IRAM
I (431) spi_flash: detected chip: generic
I (435) spi_flash: flash io: qio
W (439) spi_flash: Detected size(4096k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (453) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (488) wifi:wifi driver task: 3ffc2340, prio:23, stack:6656, core=0
I (488) system_api: Base MAC address is not set
I (490) system_api: read default base MAC address from EFUSE
I (498) wifi:wifi firmware version: eb52264
I (500) wifi:wifi certification version: v7.0
I (504) wifi:config NVS flash: enabled
I (508) wifi:config nano formating: disabled
I (512) wifi:Init data frame dynamic rx buffer num: 64
I (517) wifi:Init management frame dynamic rx buffer num: 64
I (522) wifi:Init management short buffer num: 32
I (527) wifi:Init dynamic tx buffer num: 64
I (531) wifi:Init static rx buffer size: 1600
I (535) wifi:Init static rx buffer num: 16
I (538) wifi:Init dynamic rx buffer num: 64
I (543) wifi_init: rx ba win: 32
I (546) wifi_init: tcpip mbox: 50
I (550) wifi_init: udp mbox: 6
I (554) wifi_init: tcp mbox: 6
I (558) wifi_init: tcp tx win: 5744
I (562) wifi_init: tcp rx win: 5744
I (566) wifi_init: tcp mss: 1440
I (570) wifi_init: WiFi IRAM OP enabled
I (574) wifi_init: WiFi RX IRAM OP enabled
I (579) wifi_init: LWIP IRAM OP enabled
I (584) wifi:Set ps type: 0

I (587) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (675) wifi:mode : sta (9c:9c:1f:24:df:94)
I (675) wifi:enable tsf
Waiting for AP connection...
Disconnect reason : 201
Disconnect reason : 201
I (5977) wifi:new:<11,2>, old:<1,0>, ap:<255,255>, sta:<11,2>, prof:1
I (6433) wifi:state: init -> auth (b0)
I (6461) wifi:state: auth -> assoc (0)
I (6483) wifi:state: assoc -> run (10)
I (6503) wifi:connected with 222, aid = 2, channel 11, 40D, bssid = 7c:b5:9b:f6:a2:e9
I (6503) wifi:security: WPA2-PSK, phy: bgn, rssi: -28
I (6505) wifi:pm start, type: 0

W (6526) wifi:<ba-add>idx:0 (ifx:0, 7c:b5:9b:f6:a2:e9), tid:5, ssn:2, winSize:64
I (6529) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (7486) esp_netif_handlers: sta ip: 192.168.1.100, mask: 255.255.255.0, gw: 192.168.1.1
SYSTEM EVENT STA GOT IP : 192.168.1.100
Connected to AP
I (7490) server_common: mDNS hostname set to: [dap]
I (7495) server_common: mDNS instance name set to: [DAP mDNS]
I (7502) corsacOTA: start corsacOTA thread...
Socket created
Socket binded
Socket listening
W (24875) wifi:<ba-add>idx:1 (ifx:0, 7c:b5:9b:f6:a2:e9), tid:0, ssn:1, winSize:64
Socket accepted
Handling dev attach request...
Sending header...
Sending device info...
* GET 0x02 CONFIGURATION DESCRIPTOR
Sending only first part of CONFIG
* GET 0x01 DEVICE DESCRIPTOR
* GET 0x02 CONFIGURATION DESCRIPTOR
Sending only first part of CONFIG
* GET 0x02 CONFIGURATION DESCRIPTOR
Sending ALL CONFIG
* SET CONFIGURATION
* GET 0x0F BOS DESCRIPTOR
* GET MSOS 2.0 vendor-specific descriptor
** REQUESTED list of supported languages
* GET STATUS
recv failed: errno 104
Shutting down socket and restarting...
W (245653) wifi:<ba-add>idx:2 (ifx:0, 7c:b5:9b:f6:a2:e9), tid:2, ssn:1, winSize:64
Socket accepted
Handling dev attach request...
Sending header...
Sending device info...
* GET 0x02 CONFIGURATION DESCRIPTOR
Sending only first part of CONFIG
* GET 0x01 DEVICE DESCRIPTOR
* GET 0x02 CONFIGURATION DESCRIPTOR
Sending only first part of CONFIG
* GET 0x02 CONFIGURATION DESCRIPTOR
Sending ALL CONFIG
recv failed: errno 104
Shutting down socket and restarting...
Socket accepted
Handling dev attach request...
Sending header...
Sending device info...
* GET 0x02 CONFIGURATION DESCRIPTOR
Sending only first part of CONFIG
* GET 0x01 DEVICE DESCRIPTOR
* GET 0x02 CONFIGURATION DESCRIPTOR
Sending only first part of CONFIG
* GET 0x02 CONFIGURATION DESCRIPTOR
Sending ALL CONFIG
* SET CONFIGURATION
* GET 0x0F BOS DESCRIPTOR
* GET MSOS 2.0 vendor-specific descriptor
** REQUESTED list of supported languages
* GET STATUS
recv failed: errno 104
Shutting down socket and restarting...
Socket accepted
Handling dev attach request...
Sending header...
Sending device info...
* GET 0x02 CONFIGURATION DESCRIPTOR
Sending only first part of CONFIG
* GET 0x01 DEVICE DESCRIPTOR
* GET 0x02 CONFIGURATION DESCRIPTOR
Sending only first part of CONFIG
* GET 0x02 CONFIGURATION DESCRIPTOR
Sending ALL CONFIG
* SET CONFIGURATION
* SET INTERFACE
* GET 0x0F BOS DESCRIPTOR
* GET MSOS 2.0 vendor-specific descriptor
** REQUESTED list of supported languages
* GET STATUS
* 
3. target usb comm info:
![image](https://user-images.githubusercontent.com/287193/189160240-ec68674d-2682-48be-8b90-d5ead4de7055.png)

**Comment by sczh01** [comment]
Thanks. would you test it when you are free!

**Comment by windowsair** [comment]
It looks like you are using esp32 S-series chips. I would like to remind that only support for the original esp32 chips has been added so far, work is still in progress for the C-series and S-series.

**Comment by windowsair** [comment]
Hi, this project now supports ESP32. The node ESP-32S you are using is actually ESP32. Please try using the latest version of the project.
