### ISSUE TITLE
关于SWD和JTAG引脚口的变更

### ISSUE THREAD

**Issue by xiaohuihere** [windowsair/wireless-esp8266-dap#40]
你好，我在对本项目进行二次开发时，想要修改调试有关的引脚。但是发现了以下的警告注释
![image](https://user-images.githubusercontent.com/102411813/189862920-4bd39ac5-033b-4176-9567-de9076c1f2d5.png)
请问，为什么不能更改SWD或者JTAG的引脚口呢？

**Comment by windowsair** [comment]
确切地讲，不建议修改SWDIO和SWCLK引脚。这两个引脚上的信号都是从IO_MUX上直出的，在高速时钟下可以达到最好的效果。

当然，也可以通过GPIO矩阵对信号进行重映射，但我暂时还没有试过这个
