### ISSUE TITLE
Release的固件没有正常运行

### ISSUE THREAD

**Issue by LDEDA4587** [windowsair/wireless-esp8266-dap#42]
模块是ESP-WROOM-02, 16Mbit.使用的固件是v0.2.0,下载设置如下:
![ESP-WROOM-02_1](https://user-images.githubusercontent.com/60053330/194857187-7a52187f-fc27-4239-9cb5-189fd51570a7.JPG)
启动信息如下:
![ESP-WROOM-02_2](https://user-images.githubusercontent.com/60053330/194857675-7ff627ac-0bed-47c2-80d7-b347ba09b6c5.JPG)
SPI MODE设置为QIO,DIO,DOUT启动信息都一样,在网络里也找不到AP.
v0.1.2版本的固件也试过,都是无法正常运行.
这是下载设置哪里有问题吗?

**Comment by windowsair** [comment]
使用full固件烧录到0x0

**Comment by LDEDA4587** [comment]
![ESP-WROOM-02_Full](https://user-images.githubusercontent.com/60053330/194861240-bf36fece-850a-4eba-a31b-d4c4315ea4f3.JPG)
![ESP-WROOM-02_Full_2](https://user-images.githubusercontent.com/60053330/194861275-d8aff9e7-f012-45eb-9310-c2a344a52f7d.JPG)
这样就是成功运行了吗?

**Comment by windowsair** [comment]
是的，这样就烧录成功了

**Comment by LDEDA4587** [comment]
非常感谢! 这样看来ESP-12F(Nodemcu)也是可以使用的.
