### ISSUE TITLE
使用esp32c3编译遇到的问题

### ISSUE THREAD

**Issue by banxiafeixia** [windowsair/wireless-esp8266-dap#55]
The idf.py in the project root directory is only applicable to the old ESP8266 target. Don’t use it in ESP32.
项目里提到不能用里面的这个idf.py，那应该怎么替换啊

**Comment by windowsair** [comment]
用官方sdk里自带的，不需要替换

**Comment by banxiafeixia** [comment]
我就是看这个项目好酷啊，俺也想学

**Comment by windowsair** [comment]
submodule没有下全

**Comment by banxiafeixia** [comment]
哦对，我git idf的时候，确实有报过这个错误，谢谢指点

**Comment by banxiafeixia** [comment]
问一下啊，我这没下载全的话，这应该怎么去哪里找啊？我各种方式安装下载都一直报这个错误。

**Comment by kerms** [comment]
> 问一下啊，我这没下载全的话，这应该怎么去哪里找啊？我各种方式安装下载都一直报这个错误。

You just have to do: 
`git clone --recursive your_link.git`

**Comment by banxiafeixia** [comment]
其实我recursive了很多次，compnent也升级很多次，都提示没啥好升级的，然后我就把这个#include "components/corsacOTA/src/corsacOTA.h 屏蔽掉，嗨，你猜怎么着，好使了。

**Comment by windowsair** [comment]
如果没有其他问题，我要关闭这个issue了。欢迎随时打开它
