### ISSUE TITLE
在VScode中用EIDE里的OpenOCD无法找到elaphureLink.cfg

### ISSUE THREAD

**Issue by badboyhuan** [windowsair/wireless-esp8266-dap#56]
在VScode中用EIDE开发，无法找到elaphureLink.cfg，不知道怎么操作。
选择了CMSIS-DAP.cfg,烧录显示unable to find a matching CMSIS-DAP device，没有找到设备。
但是找elaphureLink.cfg也找不到。

**Comment by windowsair** [comment]
elaphureLink只支持keil
