### ISSUE TITLE
自定义wifi连接，防止错连

### ISSUE THREAD

**Issue by jikongwudi** [windowsair/wireless-esp8266-dap#58]
能否出一个详细的教程，自定义WiFi名称与密码后，进行程序的编译，得到自定义固件（编译小白，恳请大佬解答）

**Comment by windowsair** [comment]
等待编译完成即可

**Comment by jikongwudi** [comment]
![image](https://user-images.githubusercontent.com/88077408/232128529-864148a2-b6d1-4690-978b-85f2ec91648d.png)
在线编译失败了，这可咋整
有没有更好的编译方法

**Comment by jikongwudi** [comment]
![image](https://user-images.githubusercontent.com/88077408/232130710-5aeb1ba1-942c-4a15-8970-e4290331919e.png)
wo我的界面一直是这个，我需要做些什么能够编译成功嘛，亲爱的作者

**Comment by windowsair** [comment]
麻烦更新下，试试这个版本
https://github.com/windowsair/wireless-esp8266-dap/commit/6ffe17fb137aa0e29781943daf93308d8ae1b482
