### ISSUE TITLE
esp32 ，软件复位不起作用

### ISSUE THREAD

**Issue by sq113** [windowsair/wireless-esp8266-dap#64]
![image](https://github.com/windowsair/wireless-esp8266-dap/assets/43515787/3c745738-912b-4a3f-802b-0dfef8673ab9)
![image](https://github.com/windowsair/wireless-esp8266-dap/assets/43515787/b832c3de-ed48-4182-af1e-a046a5bfbe08)

**Comment by windowsair** [comment]
能否提供一个最小的复现工程？

**Comment by sq113** [comment]
硬件esp32 stm32f103
固件  https://github.com/windowsair/wireless-esp8266-dap/releases 预编译固件
软件keil5.36  elaphureLink 1.2.0稳定版

在换成keil5.38 和 elaphureLink 最新开发版 后也是一样但是烧录结束会额外出现窗口
![image](https://github.com/windowsair/wireless-esp8266-dap/assets/43515787/4696ee92-08a2-4b17-86f7-d75123f3f377)
![image](https://github.com/windowsair/wireless-esp8266-dap/assets/43515787/fd9187e5-6518-4597-adeb-8be0c22c388b)
![image](https://github.com/windowsair/wireless-esp8266-dap/assets/43515787/37575c7f-8922-4cb8-8a1e-011ebb5b01c3)

**Comment by windowsair** [comment]
看起来像是启用了硬件复位？

方便提供下最小复现的Keil工程吗

**Comment by windowsair** [comment]
另外，请勾选下SWJ选项再测试下

**Comment by sq113** [comment]
[led.zip](https://github.com/windowsair/wireless-esp8266-dap/files/13373339/led.zip)
还是不行

**Comment by windowsair** [comment]
好的，我晚点测试下

**Comment by windowsair** [comment]
具体用的是哪款103芯片？103r8t6？

**Comment by sq113** [comment]
stm32f103rct6

**Comment by windowsair** [comment]
您好，建议您使用下面这个版本的elaphureLink再试下，在这个版本上我这里没有复现您的问题。
https://github.com/windowsair/elaphureLink/actions/runs/6614836721

记得重新安装elaphureLink驱动
