### ISSUE TITLE
经常下载不进去程序  是电脑的热点信号太弱了吗？   而且无法进行软件的复位

### ISSUE THREAD

**Issue by f0yu** [windowsair/wireless-esp8266-dap#65]
![P5%~MW~%6EB51OZM HF`G)S](https://github.com/windowsair/wireless-esp8266-dap/assets/108912136/4f4cd36d-7312-406b-bd33-bcba3c52d8b0)

**Comment by windowsair** [comment]
Timeout的话一般都是信号太差
