### ISSUE TITLE
pyocd does not detect debug probe

### ISSUE THREAD

**Issue by AILIFE4798** [windowsair/wireless-esp8266-dap#68]
esp8266 version worked just fine with usbip on keil i can upload and debug
but i want to erase flash to unlock readout protection with pyocd but it does not detect the debug probe
![image](https://github.com/windowsair/wireless-esp8266-dap/assets/142502122/0d99c1d2-b994-4c0a-bf16-d4d875661781)

**Comment by windowsair** [comment]
Hi, @AILIFE4798 ,

I haven't tested pyocd. Can the device be detected if you use openocd?

**Comment by AILIFE4798** [comment]
idk how to use openocd , and it does not support the mm32spin05pf mcu i need it for
the device is detected in device manager correctly like in the readme
![image](https://github.com/windowsair/wireless-esp8266-dap/assets/142502122/1dc075e6-9c29-4a42-ba00-a2f67797e265)

**Comment by windowsair** [comment]
If possible, could you provide more information about pyocd, such as the version you're using and related commands?

**Comment by AILIFE4798** [comment]
i installed the latest pyocd with pip
just install python first (ofcourse) then use `pip install pyocd`(vpn needed)
then to check the available debug probe use `pyocd list -p` it should show the probes like this
![image](https://github.com/windowsair/wireless-esp8266-dap/assets/142502122/2ef685f7-4b26-4f97-a96e-e9d8853a2e64)

**Comment by windowsair** [comment]
I have reproduced the problem.  It may take some time to adapt pyocd :)

**Comment by windowsair** [comment]
try this firmware

https://github.com/windowsair/wireless-esp8266-dap/actions/runs/7656753399

**Comment by AILIFE4798** [comment]
need change wifi credentials
ssid:AILIFE_SmartHome_2.4G
password:43214321
because i cannot build my self

**Comment by AILIFE4798** [comment]
ota also does not work

**Comment by windowsair** [comment]
Some of pyocd's usb operations don't seem to be well adapted.  It may take a while to fix this.

**Comment by AILIFE4798** [comment]
ok

**Comment by windowsair** [comment]
Hello, you can try the latest code in the master branch. I've done a simple test using pyocd :)

**Comment by AILIFE4798** [comment]
i have tried to use latest firmware
it can detect the probe now
but cannot erase or flash
when a target is connected correctly it says no ack received
and when i didnt connect target it says unexpected ack value 0
![image](https://github.com/windowsair/wireless-esp8266-dap/assets/142502122/92be45d0-f68b-4576-a6d9-04bca03a007f)
and there is suvior bug idk in where
cuz when i first tried this i connected the swd line wrong and when i run erase command it hangs for 30 second and entire windows os crashed with blue screen
it hapenned 2 times
 but it is not consistant i cannot reproduce it

**Comment by windowsair** [comment]
Sometimes usbip can cause BSOD. For your device, is it always unable to erase?

**Comment by AILIFE4798** [comment]
yes always hangs for a long time then says no ack received

**Comment by AILIFE4798** [comment]
usb ip on windows is really not easy maybe better way is to upload hex or bin file via a website and itll get flashed to device
or maybe gdb server via wifi

**Comment by windowsair** [comment]
Well, I don't have too many chips to test. Looks like you have mm32 and gd32 boards? If you use the gd32, will it work?

**Comment by AILIFE4798** [comment]
it is doing something this time
![image](https://github.com/windowsair/wireless-esp8266-dap/assets/142502122/6364595a-1ded-41e2-a6e1-18bc6e4ac3c3)

**Comment by AILIFE4798** [comment]
also tested on stm32f103 the single most common and most cloned chip
it did not work either
![image](https://github.com/windowsair/wireless-esp8266-dap/assets/142502122/1c73cfaa-2e04-4410-b88f-a08c6e850652)

**Comment by windowsair** [comment]
It's weird. looks like the behavior is the same between the different chips. I tested it on stm32f103rc and it work well :( 
I'll try c8 later.

**Comment by AILIFE4798** [comment]
dont have a f103rc now
or actually i do have one but it is locked and i want to keep it

**Comment by windowsair** [comment]
okay i found some problem. we should use 10MHz speed when we use esp8266.
```bash
pyocd erase -t stm32f103c8 --chip --frequency=10000000
```
