### ISSUE TITLE
Can ESP8266-DAP connect to a Wi-Fi router? 

### ISSUE THREAD

**Issue by novval** [windowsair/wireless-esp8266-dap#69]
Hi, friends!
Can ESP8266-DAP connect to a Wi-Fi router? 
Or is esp8266-dap only as an access point?
Thx!

**Comment by windowsair** [comment]
Sure, you can connect it to the router, as esp8266-dap is currently used as a station.

**Comment by novval** [comment]
Hi again!
I have a wi-fi router. A computer is connected to the Wi-fi router with an ethernet cable. I want the ESP8266-DAP to connect to the wi-fi router. And I saw this ESP8266-DAP from my computer in the Keil program.
I don't understand how to connect the ESP8266-DAP to a wi-fi router.
Thanks!
