### ISSUE TITLE
用iar显示Reading CPU status failed

### ISSUE THREAD

**Issue by 2654967934** [windowsair/wireless-esp8266-dap#71]
用iar显示
![image](https://github.com/windowsair/wireless-esp8266-dap/assets/57736494/1049dbcb-ae0f-4e3b-a862-4f5d358e8780)
用keil可以正常使用
想问iar下能正常使用的吗

**Comment by 2654967934** [comment]
试了下用IAR9.32.1版本的可以用
IAR8.30.1会显示Probe not found
IAR8.32.4会显示Reading CPU status failed
试了一下手里另一个有线正常的CMSISDAP，firmware version显示的也是V2.1，但是低版本的iar也能正常使用，不知道为什么

**Comment by windowsair** [comment]
没有试过iar，现在用的固件版本是哪个？

**Comment by 2654967934** [comment]
> 没有试过iar，现在用的固件版本是哪个？

我用的就是releases里最新的

**Comment by windowsair** [comment]
试试看主线分支里面最新的代码

**Comment by 2654967934** [comment]
> 试试看主线分支里面最新的代码

试了下情况一样

**Comment by windowsair** [comment]
我看了下 IAR8.30.1 的行为，感觉 IAR 在这个版本尝试使用的是 CMSIS-DAP v1，v1版本是不支持的。

**Comment by windowsair** [comment]
找到了 8.32.4 版本的 release note:
```
CMSIS-DAP v2
The debugger now supports the latest CMSIS-DAP standard with WinUSB transfer mode resulting in faster debug experiences when using CMSIS-DAP v2 compliant boards.
```

看起来这是第一个支持 v2 的版本

**Comment by sblpp** [comment]
大佬，能把elaphureLink 适配到IAR吗？多谢多谢

**Comment by windowsair** [comment]
> 多谢

IAR 的支持不一定能搞得到，只能先问下
